version: "3"

volumes:
    database-data:

services:
    database:
        image: postgres
        volumes:
            - database-data:/var/lib/postgresql/data
        environment: 
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: brannigan
            POSTGRES_DB: brannigan
        ports:
            - 5432:5432
    
    backend:
        build: 
            context: ./brannigans-chess-backend
            dockerfile: ./Dockerfile
        environment:
            BRANNIGANS_CHESS_DB_URL: database
        depends_on: 
            - database
        ports:
            - 8080:8080
        expose: 
            - 8080