version: "3"

volumes:
    database-data:

services:
    database:
        image: postgres
        volumes:
            - database-data:/var/lib/postgresql/data
        environment: 
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: brannigan
            POSTGRES_DB: brannigan
        ports:
            - 5432:5432