spring:
  datasource:
    url: jdbc:postgresql://${BRANNIGANS_CHESS_DB_URL:localhost}:5432/${BRANNIGANS_CHESS_DB_NAME:brannigan}
    username: brannigan
    password: ${BRANNIGANS_CHESS_DB_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

cors:
  allowed-origin: ${CHESS_ACCESS_CONTROL_ALLOW_ORIGIN:http://localhost:3000}
