name: Coverage CI

on:
  push:
    branches:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew clean build test
      - run: bash <(curl -s https://codecov.io/bash)