name: Docker Image CI

on:
  push:
    branches:
      !chore/exclude_redundant_action

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./brannigans-chess-backend --tag brannigans-chess-backend:$(date +%s)
